#!/usr/bin/env tclsh
# mkindex.tcl -- generate a per-directory index.md for an mdserver doc tree
# ============================================================================
# Walks --root recursively and writes an index.md into every directory that
# lists its subdirectories and Markdown files (titles taken from the first
# "# H1"). Meant as a companion to mdserver: instead of the server's automatic
# directory listing you get real, editable index.md landing pages.
#
# Usage:
#   tclsh mkindex.tcl --root docs
#   tclsh mkindex.tcl --root docs --title "Handbuch"
#   tclsh mkindex.tcl --root docs --dry-run
#   tclsh mkindex.tcl --root docs --force
#
# Safety: generated files carry a marker comment. Existing index.md files
# WITHOUT that marker are treated as hand-written and left untouched (unless
# --force). So re-running only refreshes the files mkindex created itself.
# ============================================================================

package require Tcl 8.6 9

set opts(root)   "."
set opts(title)  ""
set opts(force)  0
set opts(dryrun) 0
set opts(marker) "<!-- generated by mkindex.tcl -- edits will be overwritten -->"

# --- CLI ---------------------------------------------------------------------
for {set i 0} {$i < [llength $argv]} {incr i} {
    set arg [lindex $argv $i]
    switch -- $arg {
        --root    { set opts(root)  [lindex $argv [incr i]] }
        --title   { set opts(title) [lindex $argv [incr i]] }
        --force   { set opts(force)  1 }
        --dry-run { set opts(dryrun) 1 }
        --help - -h {
            puts "mkindex.tcl -- generate per-directory index.md files"
            puts ""
            puts "Options:"
            puts "  --root DIR     Document root to walk (default: .)"
            puts "  --title TEXT   H1 title for the root index (default: dir name)"
            puts "  --force        Overwrite even hand-written index.md files"
            puts "  --dry-run      Show what would be written, change nothing"
            puts "  --help         This help"
            exit 0
        }
        default {
            puts stderr "Unknown option: $arg (try --help)"
            exit 1
        }
    }
}

if {![file isdirectory $opts(root)]} {
    puts stderr "ERROR: root is not a directory: $opts(root)"
    exit 1
}
set opts(root) [file normalize $opts(root)]

# --- helpers -----------------------------------------------------------------

# First "# H1" of a Markdown file, else the file base name.
proc mdTitle {file} {
    set title [file rootname [file tail $file]]
    if {![catch {open $file r} fh]} {
        fconfigure $fh -encoding utf-8
        while {[gets $fh line] >= 0} {
            if {[regexp {^#\s+(.+)$} $line -> t]} {
                set title [string trim $t]
                break
            }
        }
        close $fh
    }
    return $title
}

# Display label of a subdirectory: its index.md H1 if present, else its name.
proc dirLabel {dir} {
    set idx [file join $dir index.md]
    if {[file exists $idx]} { return [mdTitle $idx] }
    return [file tail $dir]
}

# Write (or skip) an index.md, honouring the generated-marker safety rule.
proc writeIndex {path body} {
    global opts
    if {[file exists $path] && !$opts(force)} {
        set cur ""
        catch {
            set fh [open $path r]; fconfigure $fh -encoding utf-8
            set cur [read $fh]; close $fh
        }
        if {[string first $opts(marker) $cur] < 0} {
            puts "skip  (hand-written): [pretty $path]"
            return
        }
    }
    if {$opts(dryrun)} {
        puts "would write: [pretty $path]"
        return
    }
    set fh [open $path w]; fconfigure $fh -encoding utf-8
    puts -nonewline $fh $body
    close $fh
    puts "wrote: [pretty $path]"
}

# Path relative to root, for readable output.
proc pretty {path} {
    global opts
    set rel [string range [file normalize $path] [string length $opts(root)] end]
    return "[file tail $opts(root)][string map {\\ /} $rel]"
}

# Build and write one directory's index.md.
proc genIndex {dir} {
    global opts

    set subdirs {}
    foreach sub [lsort [glob -nocomplain -type d -directory $dir *]] {
        if {[file tail $sub] in {. ..}} continue
        lappend subdirs $sub
    }
    set files {}
    foreach f [lsort [glob -nocomplain -type f -directory $dir *.md]] {
        if {[file tail $f] eq "index.md"} continue
        lappend files $f
    }

    if {[file normalize $dir] eq $opts(root) && $opts(title) ne ""} {
        set h1 $opts(title)
    } else {
        set h1 [file tail $dir]
    }

    set body "# $h1\n\n$opts(marker)\n\n"
    set items {}
    foreach sub $subdirs {
        lappend items "- \[[dirLabel $sub]\]([file tail $sub]/)"
    }
    foreach f $files {
        lappend items "- \[[mdTitle $f]\]([file tail $f])"
    }
    if {[llength $items] == 0} {
        append body "_Keine Dokumente._\n"
    } else {
        append body [join $items "\n"] "\n"
    }

    writeIndex [file join $dir index.md] $body
}

# Post-order walk: deepest directories first, so a parent can read the H1
# of its children's freshly written index.md for nice link labels.
proc walk {dir} {
    foreach sub [lsort [glob -nocomplain -type d -directory $dir *]] {
        if {[file tail $sub] in {. ..}} continue
        walk $sub
    }
    genIndex $dir
}

walk $opts(root)
